---
- name: Apagar puerto Cisco C3650 usando RHEL como puente
  # Apuntamos directamente a la IP de tu servidor RHEL
  hosts: 10.1.4.124
  gather_facts: false

  vars:
    puerto: "GigabitEthernet1/0/23"
    ip_switch: "192.168.1.20"
    usuario_switch: "admin"
    # Cambia esto por la contraseña real de tu switch
    pass_switch: "Cu4tr0n3t*"

  tasks:
    - name: Entrar al switch desde RHEL y apagar el puerto
      ansible.builtin.expect:
        # Comando SSH nativo ejecutado desde el RHEL
        command: "ssh -o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no {{ usuario_switch }}@{{ ip_switch }}"
        timeout: 30
        responses:
          '(?i)password': "{{ pass_switch }}"
          '[>#]': 
            - "terminal length 0"
            - "configure terminal"
            - "interface {{ puerto }}"
            - "shutdown"
            - "end"
            - "write memory"
            - "exit"
